"""add is_available in resttable

Revision ID: 862b05e33363
Revises: 23c9cc89be01
Create Date: 2026-02-02 19:50:41.568027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862b05e33363'
down_revision: Union[str, Sequence[str], None] = '23c9cc89be01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'calories',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.add_column('tables', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_available')
    op.alter_column('dishes', 'calories',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
